#!/bin/bash
set -e

if [ "${CIRCLE_BRANCH}" == "v2" ]; then                                                                    
    cd packages/host-firebase
    yarn firebase deploy --token "$FIREBASE_TOKEN"
fi    
